services:
  database:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
    networks:
      - app-network
  app:
    depends_on:
      - database
    build: ./
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /Users/mairaarquino/studies/tickets-api/
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:123@database:5432/tickets_db?schema=public
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes: 
  db:

networks:
  app-network:
    driver: bridge